SAVED_PATH = "./saved/"
DB_FILE_NAME = "Tune.db"

SETTINGS_FILE_NAME = "Tune.ini"
SETTINGS_SECTION_NAME = "base"

ENCODE = "utf-8"

DIRECT_NET_NAME = "di"
GLOBAL_NET_NAME = "gl"

WSAENOTSOCK = 10038